bot:
  automerge: true
conda_forge_output_validation: true
github_actions:
  self_hosted: true
provider:
  linux: github_actions
  linux_aarch64: drone
  linux_ppc64le: travis
  osx: circle
  win: azure
